### ISSUE TITLE
Where can i find QAT int8 yolov3 accuracy or other models?

### ISSUE THREAD

**Issue by betterhalfwzm** [TexasInstruments/edgeai-mmdetection#12]
Where can i find QAT int8 yolov3 accuracy?

**Comment by mathmanu** [comment]
PTQ itself gives good accuracy for yolov3 models that we have on edgeai-mmdetection.

Have a look at this table: https://raw.githubusercontent.com/TexasInstruments/edgeai-modelzoo/master/modelartifacts/report_tda4vm.csv

models od-8070 and od-8080
