### ISSUE TITLE
cannot import name 'build_model_from_cfg' from 'xmmdet.core'

### ISSUE THREAD

**Issue by Dami1126** [TexasInstruments/edgeai-mmdetection#4]
cannot import name 'build_model_from_cfg' from 'xmmdet.core'

**Comment by mathmanu** [comment]
I was able to transfer the issue to this repository. 

Please consult this thread for a similar issue - it was fixed recently:
https://github.com/TexasInstruments/edgeai-mmdetection/issues/3

Please pull both edgeai-torchvision and edgeai-mmdetection, run the setup.sh script and try again.

If it still doesn't work, please give more details.

**Comment by Dami1126** [comment]
thank you. It work.
