### ISSUE TITLE
what the difference between quantize = 'training' and quantize = 'calibration'?

### ISSUE THREAD

**Issue by fiefdx** [TexasInstruments/edgeai-mmdetection#6]
what the difference between quantize = 'training' and quantize = 'calibration'? and what the calibration does?

I saw the train.py code as bellow
```python
    quantize = cfg.get('quantize', False)
	
    if quantize == 'calibration':
        optimizer_config = XMMDetNoOptimizerHook()
    elif fp16_cfg is not None:
        optimizer_config = Fp16OptimizerHook(
            **cfg.optimizer_config, **fp16_cfg, distributed=distributed)
    elif distributed and 'type' not in cfg.optimizer_config:
        optimizer_config = OptimizerHook(**cfg.optimizer_config)
    else:
        optimizer_config = cfg.optimizer_config
```

I thought it about 
B. Training for Quantization
C. Quantization aware Training

but, not sure if it really do that

**Comment by mathmanu** [comment]
if you set quantize = 'training' and run the training it does full Quantization Aware Training (QAT). It typically takes several epochs to complete it.

quantize = 'calibration' is a quick and approximate version of QAT. It is sufficient to do few iterations or one epoch at max. But the quantized inference accuracy may be slightly lower than that of full QAT.

More details are here: https://github.com/TexasInstruments/edgeai-torchvision/blob/master/docs/pixel2pixel/Quantization.md
